// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"t06/handler"
	"t06/repository"
	"t06/service"
)

// Injectors from wire.go:

func InitializeApp() handler.WarHandler {
	warRepository := repository.NewWarRepository()
	warService := service.NewWarService(warRepository)
	warHandler := handler.NewWarHandler(warService)
	return warHandler
}
